use_frameworks!

target 'XZCTool_Example' do
  pod 'XZCTool', :path => '../'

  target 'XZCTool_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
